### ISSUE TITLE
Is it Possibly to add an abstract display in blog

### ISSUE THREAD

**Issue by jackyliu16** [pawroman/zola-theme-terminimal#33]
Now the default operation seems is to display the whole information of the blog in the blog page, It is not convenient for others to see your other article information through this blog pager. the best ways that i though is the title of the page and the abstract

Is it possibly to display some kinds of abstract in it ? Like this one https://pawroman.github.io/zola-theme-terminimal/page/3/

**Comment by pawroman** [comment]
I think you might mean something like "summary"?

https://www.getzola.org/documentation/content/page/#summary

> You can ask Zola to create a summary if, for example, you only want to show the first paragraph of the page content in a list.

> To do so, add `<!-- more -->` in your content at the point where you want the summary to end. The content up to that point will be available separately in the [template](https://www.getzola.org/documentation/templates/pages-sections/#page-variables) via page.summary.

The theme should support this, although there might be some caveats. For one, Zola treats the "summary" as an integral part of the post content.

So... I don't really know what you mean by `abstract`. I guess if you weren't happy with the "summary approach" and wanted to show different stuff on the post list, and different in the post, the theme would have to be changed. For instance, there might be a config option to show a `description` metadata piece of the post instead of a summary.

I would definitely welcome such contribution.

**Comment by AntoniosBarotsis** [comment]
Hey @jackyliu16!

Not entirely sure what you mean by abstract but I've made some changes that allow me to specify a "description" in each post which gets rendered instead of the summary.

Example: [usage](https://github.com/AntoniosBarotsis/antoniosbarotsis.github.io/blob/61cb03847695ea910ac148e253249db545920bde/content/posts/simple_rust_macros.md?plain=1#L3), [rendered](https://antoniosbarotsis.github.io/posts/), [changes](https://github.com/AntoniosBarotsis/antoniosbarotsis.github.io/blob/61cb03847695ea910ac148e253249db545920bde/templates/macros/post.html#L8-L11).

If you think this is worth adding to the theme itself (maybe more like "if description exists, use that otherwise if summary is enabled, use that instead"), let me know and I could make a PR at some point :) @pawroman

**Comment by pawroman** [comment]
Please check out the latest version (after #53 has been merged)

**Comment by pawroman** [comment]
Hey @jackyliu16 is this still relevant?

**Comment by jackyliu16** [comment]
Sorry it took a long time to respond, given that this issue has been open for a long time.
 I'm going to close the question and check the relevant content to see how to deal with it.
