### ISSUE TITLE
Web title matching post title

### ISSUE THREAD

**Issue by lacraig2** [pawroman/zola-theme-terminimal#4]
Love this theme. It's great. One small issue I've had is that when you click on a post it keeps the title of the overall blog instead of incorporating the title of the article.

For example: https://pawroman.github.io/zola-theme-terminimal/terminimal-theme/

The title is the same as the overall site: "Zola Terminimal theme" when I'd expect it to be the title of the post: "Terminimal Theme for Zola".

**Comment by pawroman** [comment]
Hi, thanks for the praise. Most credit goes to https://github.com/panr/hugo-theme-terminal :smile: -- I have merely ported it to Zola and made some tweaks.

Thanks for reporting the issue. Should be easy enough to incorporate into the theme itself, since [index.html defines a `title` block](https://github.com/pawroman/zola-theme-terminimal/blob/master/templates/index.html#L10).

However, I don't see that as a mandatory addition to the theme, since Zola makes it easy to customize the templates of a theme. See [more info on this in Zola documentation](https://www.getzola.org/documentation/themes/extending-a-theme/).

As an example, you could customize your site by adding the title to `page.html` like this:

```
{% extends "terminimal/templates/page.html" %}

{% block title %}
    {{ page.title }}
{% endblock %}
```

**Comment by lacraig2** [comment]
That's perfect. Thank you!
