### ISSUE TITLE
Is this theme abandoned?

### ISSUE THREAD

**Issue by tlivolsi94** [pawroman/zola-theme-terminimal#57]

**Comment by pawroman** [comment]
It's not :sweat_smile: I just struggle to find the time to look into all issues and PRs properly.

**Comment by heitorPB** [comment]
@pawroman do you want more maintainers? I'd glad to help!

**Comment by pawroman** [comment]
Hey @heitorPB I'm open to it.

For starters, please check out #58 -- which fixes a bug introduces by one of the recent PRs I merged. Being a maintainer would mean having to test the incoming PRs (something I neglected to do this time!).

I'm also aiming to cut a new release, 1.2.0. What do you think? Given that we're adding OpenGraph unconditionally, should that be a 1.2.0 or 2.0.0? Technically nothing would *break*, but the theme used to explicitly mention the lack of OpenGraph and social media... Any thoughts?

**Comment by heitorPB** [comment]
Awesome!

I still need to update my blog to the new recently merged PRs and check if it is still good. Then we can officialize it :D Christmas break is not the easiest timing, but mid Jan I can spend more time here ;)

> but the theme used to explicitly mention the lack of OpenGraph and social media... Any thoughts?

Good point. OpenGraph adds metatags that make the page render nicely _on_ social media, but this change does not add social media trackers. On the other hand, "support for social media" is super vague.

I'd go with 1.2.0 because there's no backwards incompatible changes. But for me, don´t spend too much time/energy/focus on the name of the version. Or go with calendar versioning: `2023.12` and bugfixes `2023.12-1`.
